#ifndef SLIPGATES_DIRECTION_H
#define SLIPGATES_DIRECTION_H

typedef enum tDirection {
	DIRECTION_NONE,
	DIRECTION_UP,
	DIRECTION_DOWN,
	DIRECTION_LEFT,
	DIRECTION_RIGHT,
	DIRECTION_COUNT
} tDirection;

#endif // SLIPGATES_DIRECTION_H
