/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef SLIPGATES_TILE_H
#define SLIPGATES_TILE_H

#include <ace/macros.h>

#define TILE_LAYER_WALLS BV(15)
#define TILE_LAYER_FORCE_FIELDS BV(14)
#define TILE_LAYER_LETHALS BV(13)
#define TILE_LAYER_SLIPGATES BV(12)
#define TILE_LAYER_SLIPGATABLE BV(11)
#define TILE_LAYER_EXIT BV(10)
#define TILE_LAYER_BUTTON BV(9)
#define MAP_TILE_INDEX_MASK ~( \
	TILE_LAYER_WALLS | TILE_LAYER_FORCE_FIELDS | \
	TILE_LAYER_SLIPGATABLE | TILE_LAYER_LETHALS | TILE_LAYER_EXIT | \
	TILE_LAYER_BUTTON | TILE_LAYER_SLIPGATES \
)

typedef enum tTile {
	TILE_BG_1               = 0,
	TILE_SLIPGATE_1         = 1  | TILE_LAYER_SLIPGATES | TILE_LAYER_SLIPGATABLE,
	TILE_SLIPGATE_2         = 2  | TILE_LAYER_SLIPGATES | TILE_LAYER_SLIPGATABLE,
	TILE_WALL_NO_SLIPGATE_1 = 3  | TILE_LAYER_WALLS,
	TILE_WALL_1             = 4  | TILE_LAYER_WALLS | TILE_LAYER_SLIPGATABLE,
	TILE_FORCE_FIELD_1      = 5  | TILE_LAYER_FORCE_FIELDS,
	TILE_DEATH_FIELD_1      = 6  | TILE_LAYER_LETHALS,
	TILE_EXIT_1             = 7  | TILE_LAYER_WALLS | TILE_LAYER_EXIT,
	TILE_BUTTON_1           = 8  | TILE_LAYER_WALLS | TILE_LAYER_BUTTON,
	TILE_BUTTON_2           = 9  | TILE_LAYER_WALLS | TILE_LAYER_BUTTON,
	TILE_BUTTON_3           = 10 | TILE_LAYER_WALLS | TILE_LAYER_BUTTON,
	TILE_BUTTON_4           = 11 | TILE_LAYER_WALLS | TILE_LAYER_BUTTON,
	TILE_BUTTON_5           = 12 | TILE_LAYER_WALLS | TILE_LAYER_BUTTON,
	TILE_BUTTON_6           = 13 | TILE_LAYER_WALLS | TILE_LAYER_BUTTON,
	TILE_BUTTON_7           = 14 | TILE_LAYER_WALLS | TILE_LAYER_BUTTON,
	TILE_BUTTON_8           = 15 | TILE_LAYER_WALLS | TILE_LAYER_BUTTON,
	TILE_GATE_CLOSED_1      = 16 | TILE_LAYER_WALLS,
	TILE_GATE_OPEN_1        = 17,
	TILE_RECEIVER           = 18 | TILE_LAYER_WALLS,
	TILE_BOUNCER_SPAWNER    = 19 | TILE_LAYER_WALLS,
	TILE_SLIPGATABLE_OFF_1  = 20 | TILE_LAYER_WALLS,
	TILE_SLIPGATABLE_ON_1   = 21 | TILE_LAYER_WALLS | TILE_LAYER_SLIPGATABLE,
} tTile;

#endif // SLIPGATES_TILE_H
